version: "3.9"

services:
  backend:
    image: ${CI_REGISTRY_IMAGE}:latest
    ports:
      - "80:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:${DB_PASSWORD:-strongpassword}@postgres:5432/motokonig
      REDIS_HOST: redis
      SECRET_KEY: ${SECRET_KEY:-your-super-secret-key}
    restart: unless-stopped
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    external: true