version: "3.9"

services:
  backend:
    container_name: mk-api
    hostname: mk-api
    image: ${CI_REGISTRY_IMAGE}:latest
    ports:
      - "80:8000"
    environment:
      VERSION: ${VERSION}
      SECRET_KEY: ${SECRET_KEY:-your-super-secret-key}
    restart: unless-stopped
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    external: true