version: "3.9"

services:
  backend:
    container_name: mk-api
    hostname: mk-api
    image: registry.gitlab.com/motokonig/mk-backend/api-service:latest
    ports:
      - "80:8000"
    environment:
      SECRET_KEY: ${SECRET_KEY:-your-super-secret-key}
    restart: unless-stopped
    networks:
      - mk_network

volumes:
  postgres_data:

networks:
  mk_network:
    driver: bridge
    name: mk_network