services:
  # Postgres 16 — relational database
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    hostname: postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB:-motokonig}
      POSTGRES_USER: ${POSTGRES_USER:-motokonig}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-motokonig}

    volumes:
      - postgres-data:/var/lib/postgresql/data:rw

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-motokonig}"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - mk_network
    ports:
      - "5432:5432"


  # MinIO — S3‑compatible object storage
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    hostname: minio
    restart: unless-stopped

    environment:
      MINIO_ADDRESS: ":9000"
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}

    command: server --console-address ":9001" /data

    volumes:
      - minio-data:/data:rw

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

    networks:
      - mk_network

    ports:
      - "9000:9000"  # MinIO API
      - "9001:9001"  # MinIO Console

  # Redis 7 — in‑memory cache & message broker
  redis:
    image: redis:alpine
    container_name: redis
    hostname: redis
    restart: unless-stopped

    command: ["redis-server", "--appendonly", "yes"]

    volumes:
      - redis-data:/data:rw

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mk_network
    ports:
        - "6379:6379"  # Redis API

  # API service
  backend:
    container_name: mk-api
    hostname: mk-api
    build:
      dockerfile: docker/Dockerfile
      context: ..
    image: api-service:latest
    environment:
      SECRET_KEY: ${SECRET_KEY:-my-very-awesome-secret-key}
      API_VERSION: dev
      REDIS_HOST: redis
      MINIO_ENDPOINT: minio:9000
      POSTGRES_HOST: postgres
      POSTGRES_DB: motokonig
    restart: unless-stopped
    networks:
      - mk_network
    ports:
      - "8000:8000"

networks:
  mk_network:
    driver: bridge
    name: mk_network

volumes:
  caddy-data:
  caddy-config:
  postgres-data:
  minio-data:
  redis-data: