# app/domain/ports/auth_service.py
from typing import Protocol, Optional, Tuple
from app.domain.entities.user import User

class AuthService(Protocol):
    async def authenticate(self, username: str, password: str) -> Optional[User]: ...
    async def create_tokens(self, user: User) -> Tuple[str, str]: ...
    async def refresh_tokens(self, refresh_token: str) -> Optional[Tuple[str, str]]: ...
    async def logout(self, access_token: str, refresh_token: str) -> None: ...