# app/domain/ports/token_service.py
from typing import Protocol, Optional, Dict, Any
from datetime import datetime

class TokenService(Protocol):
    async def create_access_token(self, user_id: str, additional_claims: Optional[Dict[str, Any]] = None) -> str: ...
    async def create_refresh_token(self, user_id: str) -> str: ...
    async def verify_token(self, token: str) -> Optional[Dict[str, Any]]: ...
    async def revoke_token(self, token: str) -> None: ...
    async def is_token_revoked(self, token: str) -> bool: ...