# app/domain/ports/user_repository.py

from typing import Protocol, Any
from uuid import UUID

from app.domain.entities.user import User
from domain.ports.user_specification import UserSpecificationPort


class IUserRepository(Protocol):
    async def add(self, user: User) -> User: ...
    async def get(self, spec: UserSpecificationPort) -> User | None: ...
    async def list(self) -> list[User]: ...
    async def update(self, user: User) -> User: ...
    async def delete(self, user_id: UUID) -> bool: ...
