# app/domain/ports/auth.py
from typing import Protocol

from app.domain.entities.user import User


class AuthService(Protocol):
    async def authenticate(self, username: str, password: str) -> User | None: ...
    async def create_tokens(self, user: User) -> tuple[str, str]: ...
    async def refresh_tokens(self, refresh_token: str) -> tuple[str, str] | None: ...
    async def logout(self, access_token: str, refresh_token: str) -> None: ...
